# Generated by Django 5.0.3 on 2024-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('search_param', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('tehran', 'Tehran'), ('isfahan', 'Isfahan'), ('karaj', 'Karaj')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
